[profile.default]
src = "src"
out = "out"
libs = ["lib"]
is-system = true
viaIR= true
remappings=["@account-abstraction/contracts=lib/account-abstraction/contracts",'@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',"@foundry-era-contracts/contracts=lib/foundry-era-contracts/src/system-contracts/contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
